[project]
name = "gemma-3-270"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "matplotlib>=3.10.5",
    "tiktoken>=0.11.0",
    "torch==2.9.0",
    "tqdm>=4.67.1",
]
